### ISSUE TITLE
List name not appearing on printed list

### ISSUE THREAD

**Issue by crouton111** [raithos/xwing#249]
### Expected Behavior

List name should appear in the black title bar when printing.
Here's the [list](https://raithos.github.io/?f=Rebel%20Alliance&d=v5!s!1:136,-1,-1,-1:;1:136,-1,-1,-1:;1:136,-1,-1,-1:;1:136,-1,-1,-1:&sn=NoGloryBlues&obs=) I used. See attached screenshot for selected options. ![2018-12-18_10-36-38](https://user-images.githubusercontent.com/39347503/50165093-2a61d680-02b2-11e9-9f1b-5a75785c06f6.png)

### Actual Behavior

List name does not appear in the black title bar when printing. Here's the [PDF](https://github.com/raithos/xwing/files/2691213/YASB.2.pdf) exhibits the same issue as the printed page.

### Language

English 

Note: Thank you for your continued efforts with this application. You help make the X-Wing community better for everyone.

**Comment by raithos** [comment]
When I create a pdf from printing, it works normally. What browser are you using, and are you using any specific pdf program on your machine?

**Comment by crouton111** [comment]
Win 10 Firefox Quantum 64-bit. The PDF maker in the print dialog is "Adobe PDF" although the "Microsoft Print to PDF" option produces the same result. I did just try it in Chrome and it looks correct in Chrome, however that reveals a second issue that I didn't notice before in that the Firefox version didn't produce the QR codes either (Chrome did).

**Comment by crouton111** [comment]
I forgot to mention that Firefox is version 64.0.

**Comment by Patschke** [comment]
I am able to reproduce that, my firefox does neither create qr-codes nor a title on the prints.

**Comment by raithos** [comment]
So I've isolated the issue. The issue is that when printing that you need to have print background colors and images set to true in the print settings. You can set it from the following path (or by selecting print settings when the print preview is open):
File-->Page Setup-->Format & Options-->Print Background (colors & images) 

I am looking into a way to set it automatically when printing from firefox, but this is a valid workaround. I don't know yet why the list formatting is a bit broken yet, still looking into that

**Comment by raithos** [comment]
This is resolved now and is live

**Comment by crouton111** [comment]
Just took a look. QR codes display correctly, but the List Name still doesn't show up. Attached PDF.
[YASB_invisible_list_name.pdf](https://github.com/raithos/xwing/files/2765330/YASB_invisible_list_name.pdf)

**Comment by raithos** [comment]
apparently theres no way to automate it, so I just changed the header color. *shrug

**Comment by crouton111** [comment]
That works.
