### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by diablodiablo** [raithos/xwing#787]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.
Login via Twitter or Google

### Actual Behavior

State what actually happens here.
I log into Twitter or Google but YASB doesn’t log me in

I have tried on multiple browsers with no luck

### Language

The affected language(s). 
English

**Comment by raithos** [comment]
should be fixed, a bug due to something else we were working on

**Comment by diablodiablo** [comment]
Yeah still not working

I’ll try it on my computer when I get home but I really want to use it on my phone

Sent from my iPhone

On May 18, 2021, at 10:43 AM, raith ***@***.***> wrote:

﻿

Closed #787<https://github.com/raithos/xwing/issues/787>.

**Comment by raithos** [comment]
Did you try refreshing the page when you used it on your phone? It's working on all of my devices

**Comment by diablodiablo** [comment]
I actually just rebooted my phone just to make sure

I refreshed the page and I tried Google, Twitter and discord also with no luck

Sent from my iPhone

On May 18, 2021, at 12:03 PM, raith ***@***.***> wrote:

﻿

Did you try refreshing the page when you used it on your phone? It's working on all of my devices

**Comment by diablodiablo** [comment]
I just did a screen recording of the process

I’ve used it on Google Chrome mobile on my iPhone and I’ve done it on firefox too

I tried it on safari but I think I saw somewhere that it wasn’t working on that so I’ve been avoiding using that





Sent from my iPhone

On May 18, 2021, at 12:03 PM, raith ***@***.***> wrote:

﻿

Did you try refreshing the page when you used it on your phone? It's working on all of my devices

**Comment by raithos** [comment]
oh lord i hope its not a new iphone problem

**Comment by raithos** [comment]
let me ask you this, can you try logging into to yasb 1.0 and does that work? https://geordanr.github.io/xwing/

**Comment by diablodiablo** [comment]
I click on the login button but it doesn’t go anywhere it flashes though

(Funny to see only 3 factions again)
:)

I tried it on fire fox, chrome and safari

iPhone Xr
iOS 14.4.2

Sent from my iPhone

On May 18, 2021, at 12:23 PM, raith ***@***.***> wrote:

﻿

let me ask you this, can you try logging into to yasb 1.0 and does that work? https://geordanr.github.io/xwing/

**Comment by raithos** [comment]
fuck so this is definately a iphone problem. so on your iphone there is a global settings to enable cross site tracking and blocking cookies,. i think you need to disable both of those, as far as i know there's no way to whitelist yasb only

**Comment by Patschke** [comment]
I've actually recently got an iPad from/for my work, so I could in principle theoretically attempt to test if there are any options around this. Though I am not sure if I really want to... And, it's not a very recent iPad, so maybe it's not even helpful if I tried. All those annoying iOS bugs claim to be new features, right? So an old device may not (yet) experience those?

**Comment by diablodiablo** [comment]
I wasn’t able to find a global setting but I found one under Safari and I turned it off but no luck

[cid:539A7A16-615E-43E6-9112-9B14E6497822-L0-001]

Sent from my iPhone

On May 18, 2021, at 12:32 PM, raith ***@***.***> wrote:

﻿

fuck so this is definately a iphone problem. so on your iphone there is a global settings to enable cross site tracking and blocking cookies,. i think you need to disable both of those, as far as i know there's no way to whitelist yasb only

**Comment by raithos** [comment]
https://akohubteam.medium.com/how-to-enable-third-party-cookies-on-your-browsers-f9a8143b8cc5 If you did this and it still didnt work then i need you to see if it works on a pc, its possible maybe its your account but that seems really unlikely

**Comment by Patschke** [comment]
I can reproduce this behaviour on "my" iPad. However, after 15 minutes I still failed to open up a simple debug console on either Safari or Firefox. Google told me that this might in fact be impossible, and I don't see myself installing some special software on my desktop just to remote-debug that thing. At least not in the near future. Maybe I'll revisit that at some point, but for now having an iOS device did not provide any further inside for me...

**Comment by raithos** [comment]
should work now
